### ISSUE TITLE
Help to delete room names

### ISSUE THREAD

**Issue by tonilp** [juce/fiveserver#12]
Hello everyone, I need some help to delete room names from my server, when I shoot sixserver.yaml, it keeps showin![Screenshotwwererww_2](https://user-images.githubusercontent.com/13246393/143086725-c1261ff2-9877-49b1-96f3-23607c98adc0.png)
![Screenshotwwww_2](https://user-images.githubusercontent.com/13246393/143086733-15173fb4-3d62-4640-91c9-0476ba970071.png)
 (null) in the search for the whole code I didn't find anythin![Screenshotwwererww_2](https://user-images.githubusercontent.com/13246393/143086725-c1261ff2-9877-49b1-96f3-23607c98adc0.png)

**Comment by moth1995** [comment]
did you solve it? mind sharing the solution?
