### ISSUE TITLE
Issues with packet.py

### ISSUE THREAD

**Issue by LVricella** [juce/fiveserver#15]
Hi there,

I'm getting this error message, and although I searched how to fix it, it ain't working

> lib/fiveserver/model/packet.py", line 92, in __init__\n    self.md5 = hashlib.md5(b\'%s%s\' % (header,data))\n', "TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'\n"]

```
class Packet:
    """ 
    Encapsulates a PES packet, which consists 
    of three things: header, md5, data
    """
    def __init__(self, header, data):
        self.header = header
        self.data = data
        self.md5 = hashlib.md5(b'%s%s' % (header,data))
        
    def __bytes__(self):
        return b'%s%s%s' % (
                self.header,
                self.md5.digest(),
                self.data)

    def __repr__(self): 
        return 'Packet(%s,md5="%s",data:"%s")' % (
                repr(self.header),
                self.md5.hexdigest(),
                binascii.b2a_hex(self.data))

```

Any hint? Thanks!

**Comment by moth1995** [comment]
try to print the type of header and data and also print them, like the message says the function hashlib.md5 only reads bytes objects and you're sending one of them as string do something like

this is to check what's inside those variable

print(self.header)
print(self.data)

to read the type of those values

print(type(self.header))
print(type(self.data))

before line 92 maybe that will give you an idea of what its happening then once you found what value gives you that error you can do something like 

var = var.encode()

i hope it helps

**Comment by LVricella** [comment]
> try to print the type of header and data and also print them, like the message says the function hashlib.md5 only reads bytes objects and you're sending one of them as string do something like
> 
> this is to check what's inside those variable
> 
> print(self.header) print(self.data)
> 
> to read the type of those values
> 
> print(type(self.header)) print(type(self.data))
> 
> before line 92 maybe that will give you an idea of what its happening then once you found what value gives you that error you can do something like
> 
> var = var.encode()
> 
> i hope it helps

Thanks for the reply.

Everything shows as bytes type, but this one

> 2022-01-27T10:49:24+0000 [stdout#info] PacketHeader(0x436e,64,67)
> 2022-01-27T10:49:24+0000 [stdout#info] b'\x01\x01\x03\x02\x00\x00\x03\x00\x01\x02\x02\x03\x02\xd3\x91Q'
> 2022-01-27T10:49:24+0000 [stdout#info] <class 'fiveserver.model.packet.PacketHeader'>
> 2022-01-27T10:49:24+0000 [stdout#info] <class 'str'>

That's happening when I'm choosing the match settings.
Also, I see everyone without signal (with the / where it should be showing their signal bar). So, if I create a room, you will be able to join and you'll see me, but I won't see you (although if you send me a message I can still see it). I assume this is caused by this Packet issue.

Regarding the class issue, now that I've found it, how can I use the var = var.encode()? - I mean, I wouldn't know in which part of the code add it.

Thanks!

**Comment by moth1995** [comment]
Maybe is not the perfect fix but... After line 91 try this

`if isinstance(self.data,str):
      self.data=self.data.encode()
`

Not sure if it will work but worth the try

**Comment by LVricella** [comment]
> Maybe is not the perfect fix but... After line 91 try this
> 
> `if isinstance(self.data,str): self.data=self.data.encode()`
> 
> Not sure if it will work but worth the try

Alright, that fixed the class, but not the issue itself

> 2022-01-27T11:57:20+0000 [stdout#info] PacketHeader(0x436e,64,67)
> 2022-01-27T11:57:20+0000 [stdout#info] b"b'\\x01\\x01\\x03\\x02\\x00\\x00\\x03\\x00\\x01\\x02\\x02\\x03\\x02>\\xd3\\xf9'"
> 2022-01-27T11:57:20+0000 [stdout#info] <class 'fiveserver.model.packet.PacketHeader'>
> 2022-01-27T11:57:20+0000 [stdout#info] <class 'bytes'>
> 2022-01-27T11:57:20+0000 [MainService,1,190.244.16.194] Error in protocol._packetReceived: <class 'TypeError'>
> 2022-01-27T11:57:20+0000 [MainService,1,190.244.16.194] Lines: ['Traceback (most recent call last):\n', '  File "/home/ubuntu/sixserver/lib/fiveserver/protocol/__init__.py", line 109, in _packetReceived\n    self.packetReceived(pkt)\n', '  File "/home/ubuntu/sixserver/lib/fiveserver/protocol/__init__.py", line 183, in packetReceived\n    return handler(pkt)\n', '  File "/home/ubuntu/sixserver/lib/fiveserver/protocol/pes6.py", line 1284, in setGameSettings_436c\n    usr.sendData(0x436e, data)\n', '  File "/home/ubuntu/sixserver/lib/fiveserver/model/user.py", line 67, in sendData\n    self.lobbyConnection.sendData(packetId, data)\n', '  File "/home/ubuntu/sixserver/lib/fiveserver/protocol/__init__.py", line 123, in sendData\n    packet.Packet(packet.PacketHeader(id,len(data),self._count),data))\n', '  File "/home/ubuntu/sixserver/lib/fiveserver/model/packet.py", line 97, in __init__\n    self.md5 = hashlib.md5(b\'%s%s\' % (header,data))\n', "TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'\n"]
> 2022-01-27T11:57:20+0000 [MainService,1,190.244.16.194] [RECV {}]: Packet: id=0x436c, length=0x10, count=37
> 	01 01 03 02 00 00 03 00  b'........'
> 	01 02 02 03 02 3e d3 f9  b'.....>..'

As you may see "PacketHeader(0x436e,64,67)" now shows <class 'bytes'>, which is good, but if you see the error message below that, it honestly makes no sense. I pasted the whole traceback this time (maybe you see something I'm not being able to)

Thanks!

**Comment by moth1995** [comment]
Mmm weird thing, try this comment the "fix" i gave you and now go here

https://github.com/juce/fiveserver/blob/6bb0e2bd9bf7b7d74b0015357f2d542ec0c3bcaa/lib/fiveserver/protocol/pes6.py#L907

Change bytes(pkt.data) for only pkt.data, i mean just remove the convertion to bytes... May be the issue

**Comment by moth1995** [comment]
Sorry to bother but it worked?

**Comment by LVricella** [comment]
Hey Moth, first of all thanks for the genuine interest.
Well, you solved that issue for sure, but it triggered a bunch of other error messages. Leaving that aside, there's progress, now I can play with others, so the packet is working properly.

Just to clarify, Fiveserver works like a charm, but I'm trying to merge it with the old Evo-League Sixserver, that's why I'm struggling this much.

Again, thanks for your help!

**Comment by moth1995** [comment]
Oh... Well... That's a different issue, remember to specify that first, as an advice, it will be even better if you design the whole structure yourself, evoweb has a lot of failures, and its based on older version of php

**Comment by juce** [comment]
i'm going to close this because the string/bytes has been (hopefully) taken care of everywhere now, since the conversion to Python 3.
