### ISSUE TITLE
Failed to load application: No module named 'model'

### ISSUE THREAD

**Issue by LVricella** [juce/fiveserver#5]
Hello, i'm trying to run Fiveserver 0.4.9 on a VPS with CentOS 7. I made my way to the point where i have to use "./service.sh sixserver start", but it returns this:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python3.8/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/lib/python3.8/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python3.8/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/site-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python3.8/site-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python3.8/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "./etc/sixserver.tac", line 13, in <module>
    from fiveserver.config import FiveServerConfig, YamlConfig, DatabaseConfig
  File "/root/fiveserver-0.4.9/lib/fiveserver/__init__.py", line 5, in <module>
    import model, data, data6, logic
builtins.ModuleNotFoundError: No module named 'model'


Failed to load application: No module named 'model'
```

I've verified that the modules are in the respective folder, have installed all the required redistributables, and i'm stuck there.
Any help would be appreciated, and to be honest, i'm still learning to use Linux.

**Comment by juce** [comment]
you are trying to run this with Python 3.8, but the code was written for Python 2.
I will need to update it for Python 3.

**Comment by LVricella** [comment]
I will try to run it with Python 2 then, but looking forward for that update

**Comment by juce** [comment]
Working on migration to Python 3 (still incomplete, but making progress), i didn’t realize how many changes are needed, because of how strings and bytes are handled differently py2 vs py3 :(
(i might as well rewrite the whole thing in Go - wouldn’t take a lot more time..)

**Comment by juce** [comment]
i merged my Python 3 migration into master.
Try it, instead of older version. Should be easier to set up now.

**Comment by LVricella** [comment]
Much appreciated, I will try it shortly and let you know.

**Comment by LVricella** [comment]
Well @juce 
I made my way all through the "make install". It has taken me to install/upgrade a lot of redistributables, but i made it. Now the problem is, after i execute MySQL by "mysql -u root -p", i'm able to create the fiveserver database, but when i execute "create user 'fiveserver'@'%' identified by 'we9le';" it returns `MariaDB [(none)]> create user 'fiveserver'@'%' identified by 'we9le';
ERROR 1396 (HY000): Operation CREATE USER failed for 'fiveserver'@'%'`

**Comment by juce** [comment]
what version of MariaDB are you using? I just tried the commands with 10.5 and it worked fine...

If you have one of the older ones, then instead of these two commands:

`create user 'fiveserver'@'%' identified by 'we9le';`
`grant select, insert, update on fiveserver.* to 'fiveserver'@'%';`

try the old-style grant, which combines creating a user and giving it permissions - all in one command, like this:

`grant select, insert, update on fiveserver.* to 'fiveserver'@'%' identified by 'we9le';`

**Comment by juce** [comment]
Oh, i think i know why it fails for you: you already have that user created from previous attempts with Python 2. So you can probably just ignore that error, and continue with the next sql command to create tables. And if you already had the database created from before, then you should "drop" it first with:

```
drop database fiveserver;
```

Then create it anew with:

```
create database fiveserver;
grant select, insert, update on fiveserver.* to 'fiveserver'@'%' identified by 'we9le';
use fiveserver;
source ./sql/schema.sql;
```

**Comment by LVricella** [comment]
Yes, I thought that the problem was the previous user created, so i deleted it and messed up MariaDB at the same time. I reinstalled MySQL and managed to create the users and databases.
Now the problem is this, when i execute `./service.sh fiveserver start` (or sixserver), it returns `-bash: ./service.sh: Permission denied`

**Comment by juce** [comment]
hmm.. maybe file permissions are wrong somehow on `service.sh` file?
Can you do an `ls -l` and post here what it outputs?

( if service.sh doesn't have execute permissions, you can fix that by doing `chmod +x ./service.sh` )

**Comment by LVricella** [comment]
That last chmod solved it. I'm able to excecute the ./service.sh fiveserver/sixserver start, but what should appear on the screen to know that the server is running? The last thing that returns is:
`File "/root/fsenv/lib64/python3.6/site-packages/MySQLdb/connections.py", line 185, in __init__
            super().__init__(*args, **kwargs2)
        MySQLdb._exceptions.OperationalError: (2059, "Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory")`

And it stays there, doesn't let me write anything else, just stays on that message.

**Comment by sennar83** [comment]
Hi, I have this error why?
![Immagine](https://user-images.githubusercontent.com/28109903/109572311-4cd81700-7aed-11eb-83a9-9b58d3917eb8.png)

**Comment by juce** [comment]
@LVricella  i don't know man.. that looks like something isn't right with mysqlclient library.

Are you familiar with docker? Maybe try running it via docker ... it should be much simpler than wrestling with an ancient CentOS host. There are instructions in "docker" folder.

**Comment by juce** [comment]
@sennar83 that's unrelated to this thread.
You need to edit your hosts file so that it points to a working STUN server.

**Comment by sennar83** [comment]
I'm using pcsx2 emulator. In this case I must modify file host?

Il Mar 2 Mar 2021, 00:27 Anton Jouline <notifications@github.com> ha
scritto:

**Comment by LVricella** [comment]
> @LVricella i don't know man.. that looks like something isn't right with mysqlclient library.
> 
> Are you familiar with docker? Maybe try running it via docker ... it should be much simpler than wrestling with an ancient CentOS host. There are instructions in "docker" folder.

I'll try with docker then. I'm reading the Readme, is that easy? I mean, no need for all the pip.requirements and the MySQL?

**Comment by juce** [comment]
@sennar83 yeah, with the emulator scenario, i think it's whatever your host system is using - you need to modify that. So on Windows, for example, it would be `c:\windows\system32\drivers\etc\hosts`, while on Linux or Mac - it is `/etc/hosts` file.

What you need there is something like this:
```
13.57.232.177 pes6gate-ec.winning-eleven.net
212.227.67.33 we9stun.winning-eleven.net
```

Replace first IP address with where you run your fiveserver/sixserver. The second IP is the STUN server. The one in the example above should work, but if not, search internet for free STUN servers - there are lists of those around, so it is typically not a problem to find a working one.

**Comment by juce** [comment]
@LVricella it should be easier because when you build the docker image, the `docker build ...` command does all of that stuff with dependency installing, pip packages installing - automatically. MySQL database, of course you still need but you already have that part working.

**Comment by sennar83** [comment]
Thank you. Now it works. I have a question. Now I access the registration
site by typing my public ip and then: 8190.  how do i replace myip: 8190
with mysite: 8190 or mysite.org or mysite.com etc.?

Il Mer 3 Mar 2021, 18:01 Anton Jouline <notifications@github.com> ha
scritto:

**Comment by juce** [comment]
@sennar83 for that you need own a domain name.. If you don't have one, it's relatively easy to buy from companies like Amazon, GoDaddy, and more. Just search for "buy domain" on google and read up on that for all the details.

**Comment by LVricella** [comment]
@juce I've followed the README for Docker, but i can't get it to work. I went into the /docker folder, following the README, I executed "docker build -f Dockerfile -t fiveserver ..", after it ended, executed "groupadd -g 3066 five && useradd -u 3066 -g five five", then:
```
mkdir /opt/five
cp -r ../etc ../log /opt/five/
chown -R five:five /opt/five/log
chown -R five:five /opt/five/etc/data
```
And last thing:
```
docker run -d --net=host --name=fiveserver --restart=always -v /opt/five/etc:/opt/fiveserver/etc -v /opt/five/log:/opt/fiveserver/log -e SVC=fiveserver fiveserver

docker run -d --net=host --name=sixserver --restart=always -v /opt/five/etc:/opt/fiveserver/etc -v /opt/five/log:/opt/fiveserver/log -e SVC=sixserver fiveserver
```

But, what should I do next? How do I make the server online?

**Comment by juce** [comment]
@LVricella , check if the containers are running with `docker ps`
Then, if they are up, check the logs in `/opt/five/log` directory. If all is running correctly, you should see some messages in those and no errors hopefully.

**Comment by juce** [comment]
i'm closing this, as the discussion is not really relevant to original issue.
